In [1]:
# ============================================================
# NOTEBOOK 10 — WORKFORCE INTELLIGENCE
# Enterprise HR AI — Workforce Intelligence & Upskilling Platform
# ============================================================

print("=" * 70)
print("NOTEBOOK 10 — WORKFORCE INTELLIGENCE")
print("=" * 70)

print("\nModules:")
print("✓ Engagement Intelligence")
print("✓ Role Intelligence")
print("✓ Essential Skills Intelligence")
print("✓ Software Skills Intelligence")
print("✓ Role-Skill Requirements")

======================================================================
NOTEBOOK 10 — WORKFORCE INTELLIGENCE
======================================================================

Modules:
✓ Engagement Intelligence
✓ Role Intelligence
✓ Essential Skills Intelligence
✓ Software Skills Intelligence
✓ Role-Skill Requirements

In [2]:
# ============================================================
# IMPORT LIBRARIES
# ============================================================

import numpy as np
import pandas as pd

from pathlib import Path

print("✓ Libraries imported successfully.")

✓ Libraries imported successfully.

In [3]:
# ============================================================
# PROJECT PATHS
# ============================================================

CURRENT_DIR = Path.cwd()
PROJECT_ROOT = CURRENT_DIR.parent

RAW_PATH = PROJECT_ROOT / "data" / "raw"
INTEGRATED_PATH = PROJECT_ROOT / "data" / "integrated"
OUTPUT_PATH = PROJECT_ROOT / "data" / "eda_outputs"

OUTPUT_PATH.mkdir(
    parents=True,
    exist_ok=True
)

print("Project Root:")
print(PROJECT_ROOT)

print("\nRaw Data:")
print(RAW_PATH)

print("\nIntegrated Data:")
print(INTEGRATED_PATH)

print("\nOutput Data:")
print(OUTPUT_PATH)

Project Root:
C:\Users\Shubham\Desktop\enterprise_hr_ai

Raw Data:
C:\Users\Shubham\Desktop\enterprise_hr_ai\data\raw

Integrated Data:
C:\Users\Shubham\Desktop\enterprise_hr_ai\data\integrated

Output Data:
C:\Users\Shubham\Desktop\enterprise_hr_ai\data\eda_outputs

In [5]:
# ============================================================
# LOCATE ORIGINAL DATASETS
# ============================================================

def find_file(filename):

    candidates = [
        RAW_PATH / filename,
        PROJECT_ROOT / "data" / "processed" / filename,
        PROJECT_ROOT / "data" / "integrated" / filename
    ]

    for path in candidates:
        if path.exists():
            return path

    raise FileNotFoundError(
        f"Could not find {filename}"
    )


# EXACT ORIGINAL DATASET FILENAMES

attrition_file = find_file(
    "employee_attrition.csv"
)

performance_file = find_file(
    "hr_performance_engagement.csv"
)

occupation_file = find_file(
    "occupation_data.csv"
)

essential_file = find_file(
    "essential_skills.csv"
)

software_file = find_file(
    "software_skills.csv"
)


print("✓ All 5 original datasets located.")

print("\nFiles:")
print("✓", attrition_file.name)
print("✓", performance_file.name)
print("✓", occupation_file.name)
print("✓", essential_file.name)
print("✓", software_file.name)

✓ All 5 original datasets located.

Files:
✓ employee_attrition.csv
✓ hr_performance_engagement.csv
✓ occupation_data.csv
✓ essential_skills.csv
✓ software_skills.csv

In [6]:
# ============================================================
# LOAD ORIGINAL DATASETS
# ============================================================

attrition_df = pd.read_csv(attrition_file)
performance_df = pd.read_csv(performance_file)
occupation_df = pd.read_csv(occupation_file)
essential_df = pd.read_csv(essential_file)
software_df = pd.read_csv(software_file)

print("DATASET SHAPES")
print("=" * 60)

print(f"Employee Attrition       : {attrition_df.shape}")
print(f"Performance & Engagement : {performance_df.shape}")
print(f"Occupation Data          : {occupation_df.shape}")
print(f"Essential Skills         : {essential_df.shape}")
print(f"Software Skills          : {software_df.shape}")

DATASET SHAPES
============================================================
Employee Attrition       : (1470, 35)
Performance & Engagement : (5000, 13)
Occupation Data          : (1016, 3)
Essential Skills         : (18200, 15)
Software Skills          : (31821, 7)

In [8]:
# ============================================================
# PERFORMANCE & ENGAGEMENT DATA
# ============================================================

print("Performance & Engagement Columns:")
print("=" * 60)

for col in performance_df.columns:
    print(f"✓ {col}")

Performance & Engagement Columns:
============================================================
✓ Employee ID
✓ Name
✓ Department
✓ Job Role
✓ Performance Score
✓ KPI Score
✓ Attendance (%)
✓ Peer Rating
✓ Task Completion (%)
✓ Work Hours Logged
✓ Manager Feedback
✓ Training Hours
✓ Promotion Eligibility

In [9]:
# ============================================================
# DEPARTMENT ENGAGEMENT INTELLIGENCE
# ============================================================

department_engagement = (
    performance_df
    .groupby("Department")
    .agg(
        Employee_Count=("Employee ID", "nunique"),
        Avg_Performance_Score=("Performance Score", "mean"),
        Avg_KPI_Score=("KPI Score", "mean"),
        Avg_Attendance=("Attendance (%)", "mean"),
        Avg_Peer_Rating=("Peer Rating", "mean"),
        Avg_Task_Completion=("Task Completion (%)", "mean"),
        Avg_Work_Hours=("Work Hours Logged", "mean"),
        Avg_Manager_Feedback=("Manager Feedback", "mean"),
        Avg_Training_Hours=("Training Hours", "mean")
    )
    .reset_index()
)

print("✓ Department engagement metrics calculated.")

display(department_engagement)

✓ Department engagement metrics calculated.

,Department,Employee_Count,Avg_Performance_Score,Avg_KPI_Score,Avg_Attendance,Avg_Peer_Rating,Avg_Task_Completion,Avg_Work_Hours,Avg_Manager_Feedback,Avg_Training_Hours
0,Finance,1016,75.158465,77.392628,87.549596,4.010630,84.938829,45.017717,3.974803,15.474409
1,HR,1010,75.825743,77.664614,87.274475,3.995743,85.398257,45.070297,3.991089,14.590099
2,IT,974,74.680698,77.445390,87.661776,3.983060,84.813018,44.910678,4.023101,14.636550
3,Marketing,965,73.859067,76.904415,87.256943,4.026218,84.960218,44.825907,4.039171,15.050777
4,Sales,1035,74.337198,77.495884,87.584995,3.985604,84.781961,44.821256,3.982415,14.633816

In [10]:
# ============================================================
# ENGAGEMENT INDEX
# ============================================================

engagement_components = [
    "Avg_Performance_Score",
    "Avg_KPI_Score",
    "Avg_Attendance",
    "Avg_Peer_Rating",
    "Avg_Task_Completion",
    "Avg_Manager_Feedback"
]

for col in engagement_components:
    min_value = department_engagement[col].min()
    max_value = department_engagement[col].max()

    if max_value == min_value:
        department_engagement[col + "_Norm"] = 1.0
    else:
        department_engagement[col + "_Norm"] = (
            (department_engagement[col] - min_value)
            / (max_value - min_value)
        )

department_engagement["Engagement_Index"] = (
    department_engagement[
        [col + "_Norm" for col in engagement_components]
    ]
    .mean(axis=1)
    * 100
)

print("✓ Engagement Index calculated on a 0–100 scale.")

display(
    department_engagement[
        [
            "Department",
            "Employee_Count",
            "Engagement_Index"
        ]
    ]
)

✓ Engagement Index calculated on a 0–100 scale.

  Department  Employee_Count  Engagement_Index
0    Finance            1016         48.652996
1         HR            1010         59.836585
2         IT             974         48.835476
3  Marketing             965         38.153967
4      Sales            1035         33.478613

In [11]:
# ============================================================
# ENGAGEMENT LEVEL
# ============================================================

def engagement_level(score):

    if score >= 70:
        return "HIGH"

    elif score >= 40:
        return "MEDIUM"

    else:
        return "LOW"


department_engagement["Engagement_Level"] = (
    department_engagement["Engagement_Index"]
    .apply(engagement_level)
)

print("✓ Engagement levels assigned.")

display(
    department_engagement[
        [
            "Department",
            "Engagement_Index",
            "Engagement_Level"
        ]
    ]
)

✓ Engagement levels assigned.

  Department  Engagement_Index Engagement_Level
0    Finance         48.652996           MEDIUM
1         HR         59.836585           MEDIUM
2         IT         48.835476           MEDIUM
3  Marketing         38.153967              LOW
4      Sales         33.478613              LOW

In [12]:
# ============================================================
# JOB ROLE INTELLIGENCE
# ============================================================

role_intelligence = (
    performance_df
    .groupby(["Department", "Job Role"])
    .agg(
        Employee_Count=("Employee ID", "nunique"),
        Avg_Performance_Score=("Performance Score", "mean"),
        Avg_KPI_Score=("KPI Score", "mean"),
        Avg_Attendance=("Attendance (%)", "mean"),
        Avg_Task_Completion=("Task Completion (%)", "mean"),
        Avg_Training_Hours=("Training Hours", "mean"),
        Promotion_Eligible_Count=(
            "Promotion Eligibility",
            lambda x: (x == "Yes").sum()
        )
    )
    .reset_index()
)

role_intelligence["Promotion_Eligibility_Rate"] = (
    role_intelligence["Promotion_Eligible_Count"]
    / role_intelligence["Employee_Count"]
    * 100
)

print("✓ Job role intelligence calculated.")

display(role_intelligence.head(20))

✓ Job role intelligence calculated.

,Department,Job Role,Employee_Count,Avg_Performance_Score,Avg_KPI_Score,Avg_Attendance,Avg_Task_Completion,Avg_Training_Hours,Promotion_Eligible_Count,Promotion_Eligibility_Rate
0,Finance,Accountant,355,76.571831,77.243521,88.166338,85.218338,15.211268,61,17.183099
1,Finance,Auditor,333,74.360360,77.967628,87.349009,84.687057,15.027027,39,11.711712
2,Finance,Financial Analyst,328,74.439024,76.970244,87.085732,84.891921,16.213415,44,13.414634
3,HR,Employee Relations,344,75.319767,77.196744,86.959680,85.353198,14.840116,49,14.244186
4,HR,HR Manager,325,75.960000,77.694708,87.132554,86.162831,14.120000,49,15.076923
5,HR,Recruitment Specialist,341,76.208211,78.107918,87.727302,84.715015,14.785924,56,16.422287
6,IT,Cybersecurity Specialist,345,75.052174,77.201159,87.887333,84.837101,15.171014,46,13.333333
7,IT,Data Analyst,311,75.446945,77.624534,87.663601,83.771029,14.109325,48,15.434084
8,IT,Software Engineer,318,73.528302,77.535157,87.415283,85.805943,14.572327,35,11.006289
9,Marketing,Content Strategist,309,74.579288,77.436278,86.982977,84.798479,14.611650,52,16.828479
10,Marketing,Marketing Executive,330,74.578788,76.497455,87.345121,85.032030,15.251515,41,12.424242
11,Marketing,SEO Specialist,326,72.447853,76.812239,87.427362,85.040828,15.263804,37,11.349693
12,Sales,Account Manager,343,74.055394,77.335918,87.179300,84.739825,14.865889,45,13.119534
13,Sales,Business Development,348,75.183908,77.410029,88.266063,84.560948,14.712644,49,14.080460
14,Sales,Sales Executive,344,73.761628,77.742238,87.300523,85.047558,14.322674,44,12.790698

In [13]:
# ============================================================
# O*NET OCCUPATION INTELLIGENCE
# ============================================================

occupation_intelligence = occupation_df[
    [
        "O*NET-SOC Code",
        "Title",
        "Description"
    ]
].copy()

print(
    f"✓ Occupation records: "
    f"{len(occupation_intelligence)}"
)

display(
    occupation_intelligence.head(10)
)

✓ Occupation records: 1016

,O*NET-SOC Code,Title,Description
0,11-1011.00,Chief Executives,Determine and formulate policies and provide o...
1,11-1011.03,Chief Sustainability Officers,"Communicate and coordinate with management, sh..."
2,11-1021.00,General and Operations Managers,"Plan, direct, or coordinate the operations of ..."
3,11-1031.00,Legislators,"Develop, introduce, or enact laws and statutes..."
4,11-2011.00,Advertising and Promotions Managers,"Plan, direct, or coordinate advertising polici..."
5,11-2021.00,Marketing Managers,"Plan, direct, or coordinate marketing policies..."
6,11-2022.00,Sales Managers,"Plan, direct, or coordinate the actual distrib..."
7,11-2032.00,Public Relations Managers,"Plan, direct, or coordinate activities designe..."
8,11-2033.00,Fundraising Managers,"Plan, direct, or coordinate activities to soli..."
9,11-3012.00,Administrative Services Managers,"Plan, direct, or coordinate one or more admini..."

In [14]:
# ============================================================
# ESSENTIAL SKILLS PREPARATION
# ============================================================

essential_skills = essential_df.copy()

essential_skills["Data Value"] = pd.to_numeric(
    essential_skills["Data Value"],
    errors="coerce"
)

essential_skills = essential_skills.dropna(
    subset=[
        "O*NET-SOC Code",
        "Title",
        "Element Name",
        "Scale Name",
        "Data Value"
    ]
)

print(
    f"✓ Valid essential-skill records: "
    f"{len(essential_skills)}"
)

print("\nScale types found:")
print(
    essential_skills["Scale Name"].value_counts()
)

✓ Valid essential-skill records: 18200

Scale types found:
Importance    9100
Level         9100
Name: Scale Name, dtype: int64

In [15]:
# ============================================================
# ESSENTIAL SKILLS PREPARATION
# ============================================================

essential_skills = essential_df.copy()

essential_skills["Data Value"] = pd.to_numeric(
    essential_skills["Data Value"],
    errors="coerce"
)

essential_skills = essential_skills.dropna(
    subset=[
        "O*NET-SOC Code",
        "Title",
        "Element Name",
        "Scale Name",
        "Data Value"
    ]
)

print(
    f"✓ Valid essential-skill records: "
    f"{len(essential_skills)}"
)

print("\nScale types found:")
print(
    essential_skills["Scale Name"].value_counts()
)

✓ Valid essential-skill records: 18200

Scale types found:
Importance    9100
Level         9100
Name: Scale Name, dtype: int64

In [16]:
# ============================================================
# SOFTWARE SKILLS PREPARATION
# ============================================================

software_skills = software_df.copy()

software_skills = software_skills.dropna(
    subset=[
        "O*NET-SOC Code",
        "Title",
        "Element Name"
    ]
)

print(
    f"✓ Valid software-skill records: "
    f"{len(software_skills)}"
)

print("\nIn Demand values:")
print(
    software_skills["In Demand"].value_counts(dropna=False)
)

print("\nHot Technology values:")
print(
    software_skills["Hot Technology"].value_counts(dropna=False)
)

✓ Valid software-skill records: 31821

In Demand values:
N    29396
Y     2425
Name: In Demand, dtype: int64

Hot Technology values:
N    20250
Y    11571
Name: Hot Technology, dtype: int64

In [17]:
# ============================================================
# SOFTWARE SKILL INTELLIGENCE
# ============================================================

software_skill_requirements = (
    software_skills
    .groupby(
        [
            "O*NET-SOC Code",
            "Title",
            "Element Name"
        ],
        as_index=False
    )
    .agg(
        Hot_Technology=("Hot Technology", "max"),
        In_Demand=("In Demand", "max"),
        Workplace_Example=("Workplace Example", "first")
    )
)

print(
    f"✓ Software skill requirement records: "
    f"{len(software_skill_requirements)}"
)

display(
    software_skill_requirements.head(10)
)

✓ Software skill requirement records: 12684

,O*NET-SOC Code,Title,Element Name,Hot_Technology,In_Demand,Workplace_Example
0,11-1011.00,Chief Executives,Accounting software,Y,N,ComputerEase construction accounting software
1,11-1011.00,Chief Executives,Analytical or scientific software,N,N,Lyris HQ Web-Analytics Solution
2,11-1011.00,Chief Executives,Content workflow software,Y,N,Atlassian JIRA
3,11-1011.00,Chief Executives,Customer relationship management CRM software,N,N,Blackbaud The Raiser's Edge
4,11-1011.00,Chief Executives,Data base management system software,N,N,Relational database management software
5,11-1011.00,Chief Executives,Data base reporting software,N,N,Database reporting software
6,11-1011.00,Chief Executives,Data base user interface and query software,Y,N,AdSense Tracker
7,11-1011.00,Chief Executives,Desktop publishing software,N,N,Microsoft Publisher
8,11-1011.00,Chief Executives,Document management software,Y,N,Adobe Acrobat
9,11-1011.00,Chief Executives,Electronic mail software,Y,Y,Email software

In [19]:
# ============================================================
# RECOVER ESSENTIAL SKILL REQUIREMENTS
# ============================================================

essential_skills = essential_df.copy()

essential_skills["Data Value"] = pd.to_numeric(
    essential_skills["Data Value"],
    errors="coerce"
)

essential_skills = essential_skills.dropna(
    subset=[
        "O*NET-SOC Code",
        "Title",
        "Element Name",
        "Scale Name",
        "Data Value"
    ]
)

essential_skill_requirements = (
    essential_skills
    .pivot_table(
        index=[
            "O*NET-SOC Code",
            "Title",
            "Element Name"
        ],
        columns="Scale Name",
        values="Data Value",
        aggfunc="mean"
    )
    .reset_index()
)

essential_skill_requirements.columns.name = None

essential_skill_requirements = (
    essential_skill_requirements
    .rename(
        columns={
            "Importance": "Skill_Importance",
            "Level": "Skill_Level"
        }
    )
)

print("✓ Essential skill requirements recreated.")
print(f"Records: {len(essential_skill_requirements)}")

display(essential_skill_requirements.head(10))

✓ Essential skill requirements recreated.
Records: 9100

,O*NET-SOC Code,Title,Element Name,Skill_Importance,Skill_Level
0,11-1011.00,Chief Executives,Active Learning,3.75,4.50
1,11-1011.00,Chief Executives,Active Listening,4.00,4.75
2,11-1011.00,Chief Executives,Critical Thinking,4.38,4.75
3,11-1011.00,Chief Executives,Learning Strategies,3.12,3.75
4,11-1011.00,Chief Executives,Mathematics,3.25,3.50
5,11-1011.00,Chief Executives,Monitoring,4.00,5.25
6,11-1011.00,Chief Executives,Reading Comprehension,4.12,4.62
7,11-1011.00,Chief Executives,Science,1.62,0.75
8,11-1011.00,Chief Executives,Speaking,4.25,4.75
9,11-1011.00,Chief Executives,Writing,4.12,4.38

In [20]:
# ============================================================
# RECOVER SOFTWARE SKILL REQUIREMENTS
# ============================================================

software_skills = software_df.copy()

software_skills = software_skills.dropna(
    subset=[
        "O*NET-SOC Code",
        "Title",
        "Element Name"
    ]
)

software_skill_requirements = (
    software_skills
    .groupby(
        [
            "O*NET-SOC Code",
            "Title",
            "Element Name"
        ],
        as_index=False
    )
    .agg(
        Hot_Technology=("Hot Technology", "max"),
        In_Demand=("In Demand", "max"),
        Workplace_Example=("Workplace Example", "first")
    )
)

print("✓ Software skill requirements recreated.")
print(f"Records: {len(software_skill_requirements)}")

display(software_skill_requirements.head(10))

✓ Software skill requirements recreated.
Records: 12684

,O*NET-SOC Code,Title,Element Name,Hot_Technology,In_Demand,Workplace_Example
0,11-1011.00,Chief Executives,Accounting software,Y,N,ComputerEase construction accounting software
1,11-1011.00,Chief Executives,Analytical or scientific software,N,N,Lyris HQ Web-Analytics Solution
2,11-1011.00,Chief Executives,Content workflow software,Y,N,Atlassian JIRA
3,11-1011.00,Chief Executives,Customer relationship management CRM software,N,N,Blackbaud The Raiser's Edge
4,11-1011.00,Chief Executives,Data base management system software,N,N,Relational database management software
5,11-1011.00,Chief Executives,Data base reporting software,N,N,Database reporting software
6,11-1011.00,Chief Executives,Data base user interface and query software,Y,N,AdSense Tracker
7,11-1011.00,Chief Executives,Desktop publishing software,N,N,Microsoft Publisher
8,11-1011.00,Chief Executives,Document management software,Y,N,Adobe Acrobat
9,11-1011.00,Chief Executives,Electronic mail software,Y,Y,Email software

In [21]:
# ============================================================
# COMBINED ROLE-SKILL INTELLIGENCE
# ============================================================

essential_combined = (
    essential_skill_requirements[
        [
            "O*NET-SOC Code",
            "Title",
            "Element Name",
            "Skill_Importance",
            "Skill_Level"
        ]
    ]
    .copy()
)

essential_combined["Skill_Type"] = "Essential"
essential_combined["Hot_Technology"] = np.nan
essential_combined["In_Demand"] = np.nan
essential_combined["Workplace_Example"] = np.nan


software_combined = (
    software_skill_requirements[
        [
            "O*NET-SOC Code",
            "Title",
            "Element Name",
            "Hot_Technology",
            "In_Demand",
            "Workplace_Example"
        ]
    ]
    .copy()
)

software_combined["Skill_Type"] = "Software"
software_combined["Skill_Importance"] = np.nan
software_combined["Skill_Level"] = np.nan


role_skill_requirements = pd.concat(
    [
        essential_combined,
        software_combined[
            [
                "O*NET-SOC Code",
                "Title",
                "Element Name",
                "Skill_Importance",
                "Skill_Level",
                "Skill_Type",
                "Hot_Technology",
                "In_Demand",
                "Workplace_Example"
            ]
        ]
    ],
    ignore_index=True
)

print(
    f"✓ Combined role-skill records: "
    f"{len(role_skill_requirements)}"
)

display(
    role_skill_requirements.head(10)
)

✓ Combined role-skill records: 21784

,O*NET-SOC Code,Title,Element Name,Skill_Importance,Skill_Level,Skill_Type,Hot_Technology,In_Demand,Workplace_Example
0,11-1011.00,Chief Executives,Active Learning,3.75,4.50,Essential,NaN,NaN,NaN
1,11-1011.00,Chief Executives,Active Listening,4.00,4.75,Essential,NaN,NaN,NaN
2,11-1011.00,Chief Executives,Critical Thinking,4.38,4.75,Essential,NaN,NaN,NaN
3,11-1011.00,Chief Executives,Learning Strategies,3.12,3.75,Essential,NaN,NaN,NaN
4,11-1011.00,Chief Executives,Mathematics,3.25,3.50,Essential,NaN,NaN,NaN
5,11-1011.00,Chief Executives,Monitoring,4.00,5.25,Essential,NaN,NaN,NaN
6,11-1011.00,Chief Executives,Reading Comprehension,4.12,4.62,Essential,NaN,NaN,NaN
7,11-1011.00,Chief Executives,Science,1.62,0.75,Essential,NaN,NaN,NaN
8,11-1011.00,Chief Executives,Speaking,4.25,4.75,Essential,NaN,NaN,NaN
9,11-1011.00,Chief Executives,Writing,4.12,4.38,Essential,NaN,NaN,NaN

In [22]:
# ============================================================
# ROLE SKILL SUMMARY
# ============================================================

role_skill_summary = (
    role_skill_requirements
    .groupby(
        [
            "O*NET-SOC Code",
            "Title"
        ]
    )
    .agg(
        Total_Skills=("Element Name", "nunique"),
        Essential_Skills=(
            "Skill_Type",
            lambda x: (x == "Essential").sum()
        ),
        Software_Skills=(
            "Skill_Type",
            lambda x: (x == "Software").sum()
        )
    )
    .reset_index()
)

role_skill_summary = role_skill_summary.sort_values(
    by="Total_Skills",
    ascending=False
).reset_index(drop=True)

print("ROLE SKILL REQUIREMENT SUMMARY")
print("=" * 70)

display(
    role_skill_summary.head(20)
)

ROLE SKILL REQUIREMENT SUMMARY
======================================================================

,O*NET-SOC Code,Title,Total_Skills,Essential_Skills,Software_Skills
0,15-1232.00,Computer User Support Specialists,82,10,72
1,15-1299.08,Computer Systems Engineers/Architects,79,10,69
2,15-1253.00,Software Quality Assurance Analysts and Testers,78,10,68
3,15-1211.00,Computer Systems Analysts,77,10,67
4,15-1252.00,Software Developers,77,10,67
5,15-1244.00,Network and Computer Systems Administrators,77,10,67
6,15-1241.00,Computer Network Architects,75,10,65
7,15-1242.00,Database Administrators,73,10,63
8,15-1299.09,Information Technology Project Managers,72,10,62
9,15-1243.00,Database Architects,69,10,59
10,15-1212.00,Information Security Analysts,69,10,59
11,13-1111.00,Management Analysts,69,10,59
12,11-3021.00,Computer and Information Systems Managers,68,10,58
13,15-1251.00,Computer Programmers,63,10,53
14,11-1021.00,General and Operations Managers,63,10,53
15,15-1254.00,Web Developers,62,10,52
16,15-1255.00,Web and Digital Interface Designers,62,10,52
17,15-2051.01,Business Intelligence Analysts,61,10,51
18,43-6014.00,"Secretaries and Administrative Assistants, Exc...",58,10,48
19,41-4012.00,"Sales Representatives, Wholesale and Manufactu...",56,10,46

In [23]:
# ============================================================
# HIGH-DEMAND SOFTWARE SKILLS
# ============================================================

high_demand_software = software_skills[
    software_skills["In Demand"].astype(str).str.upper() == "Y"
].copy()

high_demand_summary = (
    high_demand_software
    .groupby("Element Name")
    .agg(
        Occupation_Count=("O*NET-SOC Code", "nunique")
    )
    .reset_index()
    .sort_values(
        by="Occupation_Count",
        ascending=False
    )
    .reset_index(drop=True)
)

print("TOP HIGH-DEMAND SOFTWARE SKILLS")
print("=" * 70)

display(
    high_demand_summary.head(20)
)

TOP HIGH-DEMAND SOFTWARE SKILLS
======================================================================

                                         Element Name  Occupation_Count
0                               Office suite software               385
1                                Spreadsheet software               339
2                               Presentation software               196
3                            Electronic mail software               187
4                            Word processing software                81
5   Object or component oriented development software                77
6         Data base user interface and query software                65
7                  Computer aided design CAD software                43
8                   Analytical or scientific software                43
9                    Development environment software                42
10          Enterprise resource planning ERP software                40
11                   Computer based training software                31
12                 Graphics or photo imaging software                28
13                          Operating system software                25
14                      Geographic information system                25
15                                   Medical software                24
16   Business intelligence and data analysis software                23
17      Customer relationship management CRM software                18
18                  Web platform development software                17
19                           File versioning software                14

In [24]:
# ============================================================
# SAVE WORKFORCE INTELLIGENCE OUTPUTS
# ============================================================

engagement_output = (
    OUTPUT_PATH / "department_engagement_intelligence.csv"
)

role_output = (
    OUTPUT_PATH / "job_role_intelligence.csv"
)

occupation_output = (
    OUTPUT_PATH / "occupation_intelligence.csv"
)

skill_output = (
    OUTPUT_PATH / "role_skill_intelligence.csv"
)

summary_output = (
    OUTPUT_PATH / "role_skill_summary.csv"
)

software_output = (
    OUTPUT_PATH / "high_demand_software_skills.csv"
)


department_engagement.to_csv(
    engagement_output,
    index=False
)

role_intelligence.to_csv(
    role_output,
    index=False
)

occupation_intelligence.to_csv(
    occupation_output,
    index=False
)

role_skill_requirements.to_csv(
    skill_output,
    index=False
)

role_skill_summary.to_csv(
    summary_output,
    index=False
)

high_demand_summary.to_csv(
    software_output,
    index=False
)

print("✓ All Workforce Intelligence outputs saved.")

print("\nFiles:")
print(f"✓ {engagement_output.name}")
print(f"✓ {role_output.name}")
print(f"✓ {occupation_output.name}")
print(f"✓ {skill_output.name}")
print(f"✓ {summary_output.name}")
print(f"✓ {software_output.name}")

✓ All Workforce Intelligence outputs saved.

Files:
✓ department_engagement_intelligence.csv
✓ job_role_intelligence.csv
✓ occupation_intelligence.csv
✓ role_skill_intelligence.csv
✓ role_skill_summary.csv
✓ high_demand_software_skills.csv

In [25]:
# ============================================================
# NOTEBOOK 10 FINAL VERIFICATION
# ============================================================

print("=" * 70)
print("NOTEBOOK 10 — WORKFORCE INTELLIGENCE COMPLETE")
print("=" * 70)

print("\nEngagement Intelligence:")
print(
    f"✓ {len(department_engagement)} departments analyzed"
)

print("\nJob Role Intelligence:")
print(
    f"✓ {len(role_intelligence)} department-role combinations analyzed"
)

print("\nOccupation Intelligence:")
print(
    f"✓ {len(occupation_intelligence)} occupations available"
)

print("\nEssential Skills:")
print(
    f"✓ {len(essential_skill_requirements)} skill requirements"
)

print("\nSoftware Skills:")
print(
    f"✓ {len(software_skill_requirements)} software requirements"
)

print("\nSaved Outputs:")
print("✓ department_engagement_intelligence.csv")
print("✓ job_role_intelligence.csv")
print("✓ occupation_intelligence.csv")
print("✓ role_skill_intelligence.csv")
print("✓ role_skill_summary.csv")
print("✓ high_demand_software_skills.csv")

print("\nImportant:")
print("✓ Original 5 datasets used")
print("✓ No fabricated employee-skill mapping")
print("✓ O*NET skill requirements kept separate from employee data")

print("\n" + "=" * 70)
print("READY FOR NOTEBOOK 11")
print("=" * 70)

======================================================================
NOTEBOOK 10 — WORKFORCE INTELLIGENCE COMPLETE
======================================================================

Engagement Intelligence:
✓ 5 departments analyzed

Job Role Intelligence:
✓ 15 department-role combinations analyzed

Occupation Intelligence:
✓ 1016 occupations available

Essential Skills:
✓ 9100 skill requirements

Software Skills:
✓ 12684 software requirements

Saved Outputs:
✓ department_engagement_intelligence.csv
✓ job_role_intelligence.csv
✓ occupation_intelligence.csv
✓ role_skill_intelligence.csv
✓ role_skill_summary.csv
✓ high_demand_software_skills.csv

Important:
✓ Original 5 datasets used
✓ No fabricated employee-skill mapping
✓ O*NET skill requirements kept separate from employee data

======================================================================
READY FOR NOTEBOOK 11
======================================================================